### ISSUE TITLE
UIMA Hello world

### ISSUE THREAD

**Issue by jcolemang** [RHIT-XPrize/rhit-xprize-pipeline#1]
Get UIMA running locally and create some sort of executable "Hello World" type project to get a feel of what UIMA is even supposed to be used for

**Comment by Lewis-Kelley** [comment]
I'm currently going through this tutorial: https://uima.apache.org/doc-uima-annotator.html
It even goes into detail about how to set things up with Eclipse!

**Comment by jcolemang** [comment]
Everyone went through it!
